// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZb2Pt32Qnu6MVxt8OeZe7_aSHpzUMi8',
    appId: '1:948711390857:android:9edd53f1069fcc94c39058',
    messagingSenderId: '948711390857',
    projectId: 'gestion-servi-intel-sas',
    storageBucket: 'gestion-servi-intel-sas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyWP01lb2koN5aYOmPmvJRJYU0ltX1U4w',
    appId: '1:948711390857:ios:9c7f3f50575c91b8c39058',
    messagingSenderId: '948711390857',
    projectId: 'gestion-servi-intel-sas',
    storageBucket: 'gestion-servi-intel-sas.firebasestorage.app',
    iosClientId: '948711390857-dg4s82jd9og0b5c033grtfsqpf8u0ogk.apps.googleusercontent.com',
    iosBundleId: 'com.example.servintelOperarios',
  );
}
